#!/bin/sh
# Create a socks v5 proxy
# Uses socks.cfg file with "user", "host", and "port" variables
# http://artisan.karma-lab.net/faire-passer-trafic-tunnel-ssh

name=$(basename $0)
config_file=${name}.cfg

if [ -f "${config_file}" ]; then
	. ./${config_file}   # read user, host and port
else
	echo -e "user=\nhost=\nport=\n" > ${config_file}
	echo "config file ${config_file} created, please fill it"
	exit 2
fi

if [ -z "${user}" -o -z "${host}" -o -z "${port}" ]; then
	echo "user, host, and port variables are needed"
	exit 2
fi

ctrl_path="ctrl-socks-socket"
ssh_options="ExitOnForwardFailure=yes"

stop() {
	echo -n "Stopping ${name}... "
	ssh -S ${ctrl_path} -O exit ${user}@${host} > /dev/null 2>&1
	echo "OK"
}

start() {
	output=$(ssh -S ${ctrl_path} -O check ${user}@${host} 2>&1)
	rc=$?  # 255 when socket doest not exist, 0 otherwise
	if [ $rc -eq 0 ]; then
		echo ${output}
		exit 3
	fi
	echo -n "Starting ${name}... "
	ssh -o ${ssh_options} -MS ${ctrl_path} -nfNTD ${port} ${user}@${host}
	if [ $? -ne 0 ]; then
		echo "ERROR"
		exit 4
	else
		echo "OK"
	fi
}

check() {
	if nc -zw30 localhost ${port} &> /dev/null ; then
		if [ ! -z "$1" ]; then
			# Handle /etc/hosts
			ip=$(getent hosts ${host} | cut -d " " -f1)
			# Needs proxychains
			latency=$(proxychains nmap -sP ${ip} | grep -Eo '[[:digit:]]+\.[[:digit:]]+s' | tr -d 's')
			echo $latency
		else
			echo "actif"
		fi
		return 0
	else
		echo "inactif"
		return 1
	fi
}

case $1 in
	"start")
		start ;;
	"stop")
		stop  ;;
	"check")
		check ; exit $? ;;
	"latency")
		check latency ; exit $? ;;
	"restart")
		stop
		start  ;;
	*)
		echo "usage: ${name} start|stop|restart|check|latency"
		exit 1
esac
